<?php

namespace AppBundle\Repository;

/**
 * TeamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamsRepository extends \Doctrine\ORM\EntityRepository {

    public function findAllTeams() {
        return $this->createQueryBuilder('l')
                        ->leftJoin('l.league', 'q')
                        ->getQuery()
                        ->getResult();
    }

}
